server:
  port: 9095
spring:
  sql:
    init:
      mode: always
      platform: h2
  datasource:
    username: sa
    password: root
    url: jdbc:h2:mem:rbac-spring-boot-test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

